name: Doxygen

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen libyajl-dev

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      # Not using `CMAKE_BUILD_TYPE` since we only generate docs
      run: cmake -B ${{github.workspace}}/build -DDOCS=ON -DINCLUDE_ICU=OFF -DINCLUDE_YAJL=OFF

    - name: Build Docs
      # Actually build the docs
      run: cmake --build ${{github.workspace}}/build --target doc

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{github.workspace}}/build/doc/html
